config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pins do
  	resources :comments
  	member do
  		put "like", to: 'pins#upvote'
  	end
  end
  root to: "pins#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :pin
	belongs_to :user
end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy
	accepts_nested_attributes_for :comments
	has_attached_file  :image, styles: { medium: "100x100>" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
	acts_as_votable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :pins, dependent: :destroy
  has_many :comments, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_post

	def create
		@comment = @pin.comments.build(comment_params)
		@comment.user_id = current_user
		if @comment.save
			redirect_to pin_path(@pin), notice: 'Commented'
		end
	end

	def destroy
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to pin_comments_path, notice: 'Deleted comment'
	end

	private

	def comment_params
		params.require(:comment).permit(:description)
	end

	def set_post
		@pin = current_user.pins.find(params[:pin_id])
	end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
	before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote]
	before_action :authenticate_user!, except: [:index, :show, :upvote]

	def index
		@pins = Pin.all.order("created_at DESC")
	end

	def new
		@pin = current_user.pins.build
	end

	def create
		@pin = current_user.pins.build(pin_params)
		if @pin.save
			redirect_to @pin, notice: "Successfully created pin"
		else
			render 'new'
		end
	end

	def show
		@comment = @pin.comments
	end

	def edit
	end

	def update
		if @pin.update(pin_params)
			redirect_to @pin, notice: "Successfully updated"
		else
			render :edit
		end
	end

	def destroy
		@pin.destroy
		redirect_to root_path
	end

	def upvote
		@pin.liked_by current_user
		redirect_to @pin
	end

	private
	def pin_params
		params.require(:pin).permit(:title, :description, :image)
	end

	def find_pin
		@pin = Pin.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinterest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default">
		<div class="container">
			<div class="navbar-brand">
				<%= link_to "Pinterest", root_url %>
			</div>
			<% if user_signed_in? %>
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to "New Pin", new_pin_path %></li>
					<li><%= link_to "Account", edit_user_registration_path %></li>
					<li><%= link_to "SignOut", destroy_user_session_path, method: :delete %></li>
				</ul>
			<% else %>
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to "Sign up", new_user_registration_path %></li>
					<li><%= link_to "Sign in", new_user_session_path %></li>
				</ul>
			<% end %>
		</div>
	</nav>
	<div class="container">
		<% flash.each do |name,msg| %>
			<%= content_tag :div, msg, class: "alert alert-info" %>
		<% end %>
		<%= yield %>
	</div>
</body>
</html>

app/views/pins/_form.html.erb
<%= simple_form_for @pin, html: { class: 'form-horizontal', multipart: true } do |f| %>
	<% if @pin.errors.any? %>
		<h2><%= pluralize(@pin.errors.count, "error") %> prevented from save</h2>
		<ul>
			<% @pin.errors.full_messages.each do |error| %>
				<li><%= error %></li>
			<% end %>
		</ul>
	<% end %>
	<div class="form-group">
		<%= f.input :image, input_html: { class: 'form-control' } %>
	</div>
	<div class="form-group">
		<%= f.input :title, input_html: { class: 'form-control' } %>
	</div>
	<div class="form-group">
		<%= f.input :description, input_html: { class: 'form-control'} %>
	</div>
	<div class="form-group">
		<%= f.button :submit, class: 'btn btn-info' %>
	</div>
<% end %>

app/views/pins/edit.html.erb
<div class="col-md-6 col-md-offset-3">
	<h1>Edit Pin</h1>
	<%= render 'form' %>

	<%= link_to "Cancel", @pin %>
</div>

app/views/pins/index.html.erb
<div id="pins" class="transitions-enabled">
	<% @pins.each do |pin| %>
		<div class="box panel panel-default">
			<%= link_to (image_tag pin.image.url), pin %>
				<div class="panel-body">
					<h2><%= link_to pin.title, pin %></h2>
					<p class="user">
						Submitted by <%= pin.user.name %>
					</p>
				</div>
				<div class="panel-footer">
					<span class="glyphicon glyphicon-heart">
						<%= pin.votes_for.size %>
					</span>
				</div>
		</div>
	<% end %>
</div>

app/views/pins/new.html.erb
<div class="panel panel-default">
	<div class='panel-body'>
		<div class="col-md-6 col-md-offset-3">
			<h1>New Pin</h1>
			<%= render 'form' %>
			<%= link_to "Back", root_path %>
		</div>
	</div>
</div>

app/views/pins/show.html.erb
<div id="pin_show" class="row">
	<div class="col-md-8 col-md-offset-2 w3-card-8">
		<div class="panel panel-default">
			<div class="panel-heading pin_image">
				<p><%= image_tag @pin.image.url(:medium) %></p>
			</div>
			<div class="panel-body">
				<h1><%= @pin.title %></h1>
				<p class="description"><%= @pin.description %></p>
			</div>
			<div class="panel-footer">
				<div class="row">
					<div class="col-md-6">
						<p class="user">Submitted by <%= @pin.user.name %></p>
					</div>
					<div class="col-md-6">
						<div class="pull-right btn-group"
							<br />
							<%= link_to like_pin_path(@pin), method: :put, class: 'btn btn-default' do %>
								<span class="glyphicon glyphicon-heart">
									<%= @pin.votes_for.size %>
								</span>
							<% end %>
							<% if user_signed_in? %>
								<%= link_to "Edit", edit_pin_path(@pin), class: 'btn btn-default' %>
								<%= link_to "Delete", pin_path, method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-default' %>
							<% end %>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<% @comment.each do |c| %>
					<%= c.description %>
			<% end %>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<%= render 'shared/comment_form' %>
		</div>
		
	</div>
</div>

app/views/shared/_comment_form.html.erb
<%= simple_form_for [@pin, @pin.comments.new], html: { class: 'form-horizontal' } do |f| %>
	<div class="form-group">
		<%= f.input :description, as: :text, input_html: { class: 'form-control' } %>
	</div>
	<div class="form-group">
		<%= f.button :submit, class: 'btn btn-info' %>
	</div>
<% end %>